<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="HangfireJobs\Jobs\EmailJob\**" />
	  <EmbeddedResource Remove="HangfireJobs\Jobs\EmailJob\**" />
	  <None Remove="HangfireJobs\Jobs\EmailJob\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CloudinaryDotNet" Version="1.27.5" />
		<PackageReference Include="FluentEmail.Core" Version="3.0.2" />
		<PackageReference Include="FluentEmail.Smtp" Version="3.0.2" />
		<PackageReference Include="FirebaseAdmin" Version="3.4.0" />
		<PackageReference Include="Google.Apis.Auth" Version="1.71.0" />
		<PackageReference Include="Microsoft.AspNetCore.DataProtection.EntityFrameworkCore" Version="8.0.0" />
		<PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="5.0.17" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0" />
		<PackageReference Include="Stripe.net" Version="48.2.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\TechMeter.Application\TechMeter.Application.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="HangfireJobs\Jobs\" />
		<Folder Include="Migrations\" />
	</ItemGroup>

</Project>
